"""Re-label EveryAyah CSV files with Tajweed phoneme tokens.

Reads the existing Arabic-text CSVs (everyayah_train.csv, etc.) and produces
new CSVs where the 'transcript' column contains space-separated Tajweed
phoneme tokens generated by tajweed_g2p.text_to_phonemes().

Also generates the canonical vocab_phoneme.json for the Wav2Vec2PhonemeCTCTokenizer.

Usage:
    python relabel_with_phonemes.py
    python relabel_with_phonemes.py --preview 5     # preview first 5 rows only
"""
from __future__ import annotations

import argparse
import csv
import sys
import time
from pathlib import Path

# Add project root to path so we can import from quranic_asr_phoneme
sys.path.insert(0, str(Path(__file__).parent))

from quranic_asr_phoneme.src.tajweed_g2p import text_to_phonemes, phonemes_to_string
from quranic_asr_phoneme.src.phonemes import write_vocab_json, PHONEMES

DATA_DIR = Path(__file__).parent / "data" / "everyayah_full"

# Input/output file pairs
SPLITS = [
    ("everyayah_train.csv",  "everyayah_train_tajweed.csv"),
    ("everyayah_dev.csv",    "everyayah_dev_tajweed.csv"),
    ("everyayah_test.csv",   "everyayah_test_tajweed.csv"),
]


def relabel_csv(in_path: Path, out_path: Path, preview: int = 0) -> int:
    """Convert one CSV file from Arabic text to Tajweed phoneme labels.

    Args:
        in_path:  Input CSV with columns [wav_filename, wav_filesize, transcript]
                  where transcript is Arabic text with diacritics.
        out_path: Output CSV with same columns but transcript replaced by
                  space-separated Tajweed phoneme tokens.
        preview:  If > 0, only process first N rows and print them.

    Returns:
        Number of rows written.
    """
    rows_written = 0
    rows_skipped = 0

    with open(in_path, "r", encoding="utf-8") as f_in, \
         open(out_path, "w", encoding="utf-8", newline="") as f_out:

        reader = csv.DictReader(f_in)
        writer = csv.DictWriter(f_out, fieldnames=["wav_filename", "wav_filesize", "transcript"])
        writer.writeheader()

        for i, row in enumerate(reader):
            if preview > 0 and i >= preview:
                break

            arabic_text = row.get("transcript", "").strip()
            wav_filename = row.get("wav_filename", "").strip()
            wav_filesize = row.get("wav_filesize", "").strip()

            if not arabic_text or not wav_filename:
                rows_skipped += 1
                continue

            # Convert Arabic text → Tajweed phoneme sequence
            try:
                phonemes = text_to_phonemes(arabic_text)
                phoneme_str = phonemes_to_string(phonemes)
            except Exception as e:
                print(f"  [WARN] row {i}: failed to phonemise '{arabic_text[:50]}...': {e}")
                rows_skipped += 1
                continue

            if not phoneme_str.strip():
                rows_skipped += 1
                continue

            if preview > 0:
                print(f"\n  Row {i}:")
                print(f"    Arabic  : {arabic_text}")
                print(f"    Phonemes: {phoneme_str}")

            writer.writerow({
                "wav_filename": wav_filename,
                "wav_filesize": wav_filesize,
                "transcript": phoneme_str,
            })
            rows_written += 1

    return rows_written


def main():
    parser = argparse.ArgumentParser(description="Re-label CSVs with Tajweed phoneme tokens.")
    parser.add_argument("--preview", type=int, default=0,
                        help="Preview first N rows per split (0 = process all)")
    args = parser.parse_args()

    print("=" * 70)
    print("  Tajweed Phoneme Re-labeling")
    print("=" * 70)
    print(f"  Phoneme vocabulary: {len(PHONEMES)} tokens")
    print(f"  Tokens: {', '.join(PHONEMES[:10])} ... {', '.join(PHONEMES[-5:])}")
    print(f"  Data dir: {DATA_DIR}")
    print()

    # Generate canonical vocab JSON
    vocab_path = DATA_DIR / "vocab_phoneme.json"
    write_vocab_json(str(vocab_path))
    print(f"  [vocab] wrote {vocab_path}")
    print()

    for in_name, out_name in SPLITS:
        in_path = DATA_DIR / in_name
        out_path = DATA_DIR / out_name

        if not in_path.exists():
            print(f"  [SKIP] {in_name} not found")
            continue

        print(f"  Processing {in_name} → {out_name} ...")
        t0 = time.time()
        n = relabel_csv(in_path, out_path, preview=args.preview)
        elapsed = time.time() - t0
        print(f"  [DONE] {n} rows written in {elapsed:.1f}s")
        print()

    print("=" * 70)
    print("  Re-labeling complete!")
    print(f"  Vocab: {vocab_path}")
    print(f"  New CSVs: *_tajweed.csv in {DATA_DIR}")
    print("=" * 70)


if __name__ == "__main__":
    main()
