"""add_tajweed_errors_practice_history_daily_goals_progress_bookmarks

Revision ID: bd7dd180b6a6
Revises: 60576971a0a6
Create Date: 2026-06-22 23:08:18.304984
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7dd180b6a6'
down_revision: Union[str, None] = '60576971a0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('surah_num', sa.Integer(), nullable=False),
    sa.Column('ayah_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('daily_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('target_xp', sa.Integer(), nullable=True),
    sa.Column('current_xp', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_goals_id'), 'daily_goals', ['id'], unique=False)
    op.create_index(op.f('ix_daily_goals_user_id'), 'daily_goals', ['user_id'], unique=False)
    op.create_table('practice_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('surah', sa.Integer(), nullable=False),
    sa.Column('ayah', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_history_id'), 'practice_history', ['id'], unique=False)
    op.create_index(op.f('ix_practice_history_user_id'), 'practice_history', ['user_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('surah_num', sa.Integer(), nullable=False),
    sa.Column('ayah_num', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('last_practiced', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('tajweed_errors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('surah', sa.Integer(), nullable=False),
    sa.Column('ayah', sa.Integer(), nullable=False),
    sa.Column('word_index', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expected_text', sa.String(), nullable=False),
    sa.Column('detected_text', sa.String(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['recitation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tajweed_errors_id'), 'tajweed_errors', ['id'], unique=False)
    op.create_index(op.f('ix_tajweed_errors_session_id'), 'tajweed_errors', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tajweed_errors_session_id'), table_name='tajweed_errors')
    op.drop_index(op.f('ix_tajweed_errors_id'), table_name='tajweed_errors')
    op.drop_table('tajweed_errors')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_practice_history_user_id'), table_name='practice_history')
    op.drop_index(op.f('ix_practice_history_id'), table_name='practice_history')
    op.drop_table('practice_history')
    op.drop_index(op.f('ix_daily_goals_user_id'), table_name='daily_goals')
    op.drop_index(op.f('ix_daily_goals_id'), table_name='daily_goals')
    op.drop_table('daily_goals')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
